set(SRC_FILES
    App.cpp
    Character.cpp
    Map.cpp
    Prop.cpp
    Player.cpp
    NPC.cpp
    Vehicle.cpp
    Item.cpp
    StartMenu.cpp
    InventoryMenu.cpp
    StartMenu.cpp
    Pokemon.cpp
    PokemonMenu.cpp
    BattleManager.cpp
    BattleUI.cpp
    MoveDatabase.cpp
    PokemonDatabase.cpp
    TrainerDatabase.cpp
    PokeballAnimator.cpp
    BattleAnimator.cpp
    MapGenerator.cpp
    BattleAnimation.cpp
    AnimationPlayer.cpp
    ShopMenu.cpp
    ShopData.cpp
    ItemDatabase.cpp
    ItemHelper.cpp
    TitleScreen.cpp



)

set(INCLUDE_FILES
    App.hpp
    Character.hpp
    Map.hpp
    Prop.hpp
    Player.hpp
    NPC.hpp
    Vehicle.hpp
    GameFlags.hpp
    GameConfig.hpp
    SaveSystem.hpp
    Item.hpp
    StartMenu.hpp
    InventoryMenu.hpp
    StartMenu.hpp
    Pokemon.hpp
    PokemonMenu.hpp
    BattleManager.hpp
    BattleUI.hpp
    MoveDatabase.hpp
    PokemonDatabase.hpp
    TrainerDatabase.hpp
    PokeballAnimator.hpp
    BattleAnimator.hpp
    MapGenerator.hpp
    BattleAnimation.hpp
    AnimationPlayer.hpp
    ShopMenu.hpp
    ShopData.hpp
    ItemDatabase.hpp
    ItemHelper.hpp
    TitleScreen.hpp
)

set(TEST_FILES
)